README.md, animalfacts.py
=> Added Pangolin! Issue #4

README.md, animalfacts.py
=> Added facts for chameleons

README.md, animalfacts.py
=> Add Crocodile Facts

animalfacts.py
Added some rabbit facts as requested by #14
=> Added Rabbit facts

animalfacts.py
=> Add more squid facts

README.md, animalfacts.py
=> Add Goat facts

README.md, animalfacts.py
Added facts about orcas. Referencing #21. Happy Hacktoberfest!
=> Added orca facts

README.md, animalfacts.py
added snail to animal list and added quite a few facts
=> snail_facts

README.md, animalfacts.py
Added squirrel facts by following the contribution guide.
=> added squirrel facts

README.md, animalfacts.py
=> add snail facts

animalfacts.py
I added some facts about the cleanliness of pigs.
=> New pig facts added.

animalfacts.py
=> Added an owl fact

README.md, animalfacts.py
=> added dingo facts

README.md, animalfacts.py
Recreation of #87 after reforking. GitHub wouldn't let me commit the changes to the PR.
- Changed all facts tuples to have a trailing comma and a new line for every closing parenthesis.
- Added bear and sheep facts
- Fixed a skunk spelling mistake
=> Added bear and sheep facts - reforked

animalfacts.py
I have added alligator facts to the tuple and also changed the first letter of antartica to caps.
=> Added alligator facts

README.md, animalfacts.py
Necessary changes in animalfacts.py and README.md have been made.
=> Facts about Bison added

.gitignore, README.md, animalfacts.py
=> Added antelope facts

README.md
=> Added Lynx to README.md

animalfacts.py
=> Added Lynx Facts

README.md
=> Added Cougar facts

animalfacts.py
=> Added Yak Facts

animalfacts.py
Thanks for accepting in advance :-)
=> Added ladybug facts

animalfacts.py
Add more Gopher facts to take number of facts above 12 in response to issues #37 and #113.
=> Add more Gopher facts

README.md
=> Added Eel Facts

animalfacts.py
=> Added Vampire bat Facts

README.md
=> Added Vampire bat

animalfacts.py
=> Prune aardvark

README.md, animalfacts.py
Muskrat muskrat muskrat. Also - fixed alphabetic order of other entries (Llama).
=> Adding muskrat support

README.md, animalfacts.py
=> Added Jackal.

animalfacts.py
=> Add bison facts

animalfacts.py
=> add dingo facts.

animalfacts.py
...brought to you by the Eastern hemisphere. ;)
=> Added some more Dragon facts

README.md, animalfacts.py
=> Add chinchilla facts

README.md, animalfacts.py
=> add raven facts

README.md, animalfacts.py
=> Added cobra facts

README.md, animalfacts.py
=> Added salmon facts

README.md, animalfacts.py
=> Added anglerfish facts

README.md, animalfacts.py
Added a new animal, the beautiful toucan
=> Created New Toucan Facts

animalfacts.py
=> Chimpanzee Facts

README.md, animalfacts.py
=> Adds more sheep facts

README.md, animalfacts.py
=> Add Mongoose facts

README.md, animalfacts.py
=> Added trout facts

animalfacts.py
=> Added Whale Fact

animalfacts.py
added more Jellyfish facts under Lion's Mane Jellyfish
=> ADDED MORE JELLYFISH_FACTS

README.md, animalfacts.py
Added the great kiwi bird to the project!
=> added the Kiwi bird

README.md, animalfacts.py
Added a bit more salmon facts!
=> Adds more salmon facts

README.md, animalfacts.py
Fixed #287 and tidied up the code in various ways, including:
* Removal of extraneous tabs, whitespace, and lines between code blocks
* Setting a standard of 4 spaces for indents
* Edited the documentation to ask people to follow these standards to improve code readability
String fixing will be done in a separate PR.
Hope this is helpful.
=> Fixed #287 - Code tidy up

animalfacts.py
Added mantis shrimp to animal facts and corrected llama location per alphabetical order.
=> added mantis shrimp to animal facts.

animalfacts.py
=> Read through facts for sentence syntax, grammar, and spelling errors

animalfacts.py
Added an interesting fact about jellyfish.
Resolves #298.
=> feat(jellyfish): add fact about Jellyfish

animalfacts.py
=> Updated animalfacts.py added to LOBSTER_FACTS

animalfacts.py
=> Updated animalfacts.py added facts about axolotl

README.md, animalfacts.py
1. Added facts about Zebrafish.
2. Updated readme.md to update the list of animals.
=> Added Zebrafish Facts

README.md, animalfacts.py
=> added new animal: Vulture

README.md, animalfacts.py
Added facts about rhinos. Related to issue #298.
=> Add facts about Rhinos

animalfacts.py
Sounds strange but it's true. https://en.wikipedia.org/wiki/Virginia_opossum
=> Add opossum fact

README.md, animalfacts.py
Added Coyote facts and updated the README
=> Added Coyote facts!

README.md, animalfacts.py
This has been a nightmare to sort out for a git n00b like myself, and I feel I've really messed things up, but the upshot is that we've now got a ton of new additions and I've gone through things for consistency reasons and tidied up a bit.
I'll do this better for the next lot, promise.
=> Tidying up today's new additions

animalfacts.py
Added for https://github.com/joel-g/animal-facts-bot/issues/44
=> add deer fact

animalfacts.py
=> Added three Tuatara facts

animalfacts.py
=> Facts about Dolphin, Mink and Beaver added, for #298

README.md, animalfacts.py
=> feat: add trouser_snake

README.md, animalfacts.py
=> added the animal Chevrotain 
